// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AuthWrapper: typeof import('./src/components/features/auth/components/auth-wrapper/AuthWrapper.vue')['default']
    BantuanIcon: typeof import('./src/components/common/icons/BantuanIcon.vue')['default']
    BaseButton: typeof import('./src/components/common/base/BaseButton.vue')['default']
    BaseInput: typeof import('./src/components/common/base/BaseInput.vue')['default']
    BaseSelect: typeof import('./src/components/common/base/BaseSelect.vue')['default']
    BellCircle: typeof import('./src/components/common/icons/BellCircle.vue')['default']
    Checkbox: typeof import('./src/components/common/base/Checkbox.vue')['default']
    HomeWrapper: typeof import('./src/components/features/home/components/home-wrapper/HomeWrapper.vue')['default']
    LoginForm: typeof import('./src/components/features/auth/components/login-form/LoginForm.vue')['default']
    NasabahTable: typeof import('./src/components/features/nasabah/components/nasabah-table/NasabahTable.vue')['default']
    NotifikasiCard: typeof import('./src/components/features/notifikasi/components/notifikasi-card/NotifikasiCard.vue')['default']
    NotifikasiList: typeof import('./src/components/features/notifikasi/components/notifikasi-list/NotifikasiList.vue')['default']
    PengajuanForm: typeof import('./src/components/features/pengajuan/components/pengajuan-form/PengajuanForm.vue')['default']
    PengajuanIcon: typeof import('./src/components/common/icons/PengajuanIcon.vue')['default']
    PengajuanTable: typeof import('./src/components/features/pengajuan/components/pengajuan-table/PengajuanTable.vue')['default']
    PengajuanWrapper: typeof import('./src/components/features/pengajuan/components/pengajuan-wrapper/PengajuanWrapper.vue')['default']
    ProfileForm: typeof import('./src/components/features/auth/components/profile-form/ProfileForm.vue')['default']
    RegisterForm: typeof import('./src/components/features/auth/components/register-form/RegisterForm.vue')['default']
    RekapIcon: typeof import('./src/components/common/icons/RekapIcon.vue')['default']
    RekapTable: typeof import('./src/components/features/rekap/components/rekap-table/RekapTable.vue')['default']
    RekapWrapper: typeof import('./src/components/features/rekap/components/rekap-wrapper/RekapWrapper.vue')['default']
    TagihanForm: typeof import('./src/components/features/tagihan/components/tagihan-form/TagihanForm.vue')['default']
    TagihanIcon: typeof import('./src/components/common/icons/TagihanIcon.vue')['default']
    TagihanInvoice: typeof import('./src/components/features/tagihan/components/tagihan-invoice/TagihanInvoice.vue')['default']
    TagihanPayment: typeof import('./src/components/features/tagihan/components/tagihan-payment/TagihanPayment.vue')['default']
    TagihanTable: typeof import('./src/components/features/tagihan/components/tagihan-table/TagihanTable.vue')['default']
    TagihanWrapper: typeof import('./src/components/features/tagihan/components/tagihan-wrapper/TagihanWrapper.vue')['default']
    WebNavigation: typeof import('./src/components/WebNavigation.vue')['default']
  }
}

export { }
